services:
  backend:
    build:
      context: .
      target: development-image
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src/
      - ./config.toml:/config.toml

  postgres:
    image: "postgres:15.7-alpine3.20"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/data/
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: "exit 0"